import type { Metadata } from "next";
import Image from "next/image";
import { ArrowRight, Heart, Package, Palette } from "lucide-react";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";

export const metadata: Metadata = { title: "About", description: "Meet Joanna Sitati, founder and CEO of Anner Creatives, and discover how every handmade piece is created." };

export default function AboutPage() {
  return <main className="flex min-h-screen flex-col bg-[#fbfdff] text-[#17233b]"><SiteHeader/>
    <section className="mx-auto grid max-w-[1300px] gap-8 px-4 py-10 sm:px-8 sm:py-16 lg:grid-cols-2 lg:items-center lg:px-12">
      <div><p className="eyebrow">Meet the maker</p><h1 className="mt-3 font-serif text-4xl font-bold leading-tight sm:text-6xl"><span className="brush-text">Creativity</span> made useful, beautiful and personal.</h1><p className="mt-6 max-w-xl text-base leading-8 text-slate-600 sm:text-lg">Anner Creatives is a Kenyan handmade studio turning imagination, yarn and thoughtfully chosen materials into bags, crochet pieces and joyful everyday essentials.</p><p className="mt-4 max-w-xl leading-7 text-slate-600">Every item is made with close attention to colour, texture and the little details that make a piece feel special. Small batches allow each creation to retain the warmth and individuality of work made by human hands.</p><a href="/#collection" className="mt-7 inline-flex items-center gap-2 rounded-full bg-sky-600 px-6 py-3 text-sm font-bold text-white">Shop the collection <ArrowRight className="size-4"/></a></div>
      <div className="relative min-h-[360px] overflow-hidden rounded-[2rem] bg-[#ebe7fb] sm:min-h-[520px]"><Image src="/anner-logo.jpg" alt="Anner Creatives logo and craft motifs" fill priority className="object-contain p-8 mix-blend-multiply sm:p-14"/></div>
    </section>
    <section className="mx-auto w-full max-w-[1300px] px-4 pb-16 sm:px-8 lg:px-12"><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 sm:gap-4">{[[Heart,"Crafted with passion","Care lives in every stitch, seam and finish."],[Palette,"Designed with creativity","Playful colours and original ideas shape every piece."],[Package,"Made in small batches","Thoughtful production keeps each creation distinctive."]].map(([Icon,title,copy],index)=><article key={String(title)} className={`rounded-2xl border border-sky-100 bg-white p-4 shadow-sm sm:p-6 ${index===2?"col-span-2 sm:col-span-1":""}`}><Icon className="size-6 text-violet-600"/><h2 className="mt-4 font-serif text-base font-bold sm:text-xl">{String(title)}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{String(copy)}</p></article>)}</div></section>
    <section className="mx-auto mb-16 grid w-[calc(100%-2rem)] max-w-[1200px] overflow-hidden rounded-[2rem] bg-gradient-to-br from-sky-50 to-violet-100 sm:w-[calc(100%-4rem)] lg:grid-cols-[.85fr_1.15fr]"><div className="flex min-h-[500px] items-end justify-center px-4 pt-8 sm:min-h-[600px] sm:px-8 sm:pt-10 lg:min-h-[640px]"><Image src="/joanna-sitati-founder-transparent.png" alt="Joanna Sitati, founder and CEO of Anner Creatives" width={1012} height={1554} className="h-auto max-h-[560px] w-auto max-w-full object-contain object-top sm:max-h-[650px] lg:max-h-[680px]" sizes="(max-width:1024px) calc(100vw - 3rem), 42vw" priority/></div><div className="flex flex-col justify-center p-7 sm:p-12 lg:p-16"><p className="eyebrow">Founder & CEO</p><h2 className="mt-3 font-serif text-3xl font-bold sm:text-5xl">Joanna <span className="brush-text">Sitati</span></h2><p className="mt-5 max-w-xl leading-7 text-slate-600">Joanna brings together imagination, patience and a love for handmade work to create useful pieces filled with personality. Anner Creatives is her space for turning thoughtful ideas into beautiful everyday companions.</p></div></section>
    <SiteFooter/>
  </main>;
}
