import Image from "next/image";
import { Mail, Phone } from "lucide-react";
import { SiFacebook, SiInstagram, SiWhatsapp } from "react-icons/si";

export function SiteFooter() {
  return <footer className="mt-auto bg-[#13213d] px-4 py-8 text-white sm:px-8 sm:py-11">
    <div className="mx-auto grid max-w-[1300px] gap-7 sm:grid-cols-[1fr_auto] sm:items-center">
      <div className="flex items-center gap-3"><Image src="/anner-logo.jpg" alt="Anner Creatives" width={48} height={48} className="size-11 rounded-xl object-cover"/><div><p className="font-serif text-lg font-bold">Anner Creatives</p><p className="text-xs text-sky-200 sm:text-sm">Crafted with passion, designed with creativity.</p></div></div>
      <div className="flex flex-wrap gap-2"><a href="https://wa.me/254106819119" target="_blank" rel="noreferrer" aria-label="Chat with Anner Creatives on WhatsApp" title="WhatsApp" className="inline-flex size-9 items-center justify-center rounded-full bg-[#25D366] text-white transition hover:bg-[#20bd5a] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white sm:size-10"><SiWhatsapp className="size-4"/></a><a href="https://www.instagram.com/_anner_creatives_/" target="_blank" rel="noreferrer" aria-label="Anner Creatives on Instagram" title="Instagram" className="inline-flex size-9 items-center justify-center rounded-full bg-white/10 transition hover:bg-white/20 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white sm:size-10"><SiInstagram className="size-4 text-pink-400"/></a><a href="mailto:annercreatives7@gmail.com" aria-label="Email Anner Creatives" title="Email" className="inline-flex size-9 items-center justify-center rounded-full bg-white/10 transition hover:bg-white/20 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white sm:size-10"><Mail className="size-4 text-sky-300"/></a><a href="tel:+254106819119" aria-label="Call Anner Creatives" title="Call" className="inline-flex size-9 items-center justify-center rounded-full bg-white/10 transition hover:bg-white/20 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white sm:size-10"><Phone className="size-4 text-violet-300"/></a><a href="https://www.facebook.com/profile.php?id=61558038923823" target="_blank" rel="noreferrer" title="Facebook" aria-label="Anner Creatives on Facebook" className="inline-flex size-9 items-center justify-center rounded-full bg-white/10 transition hover:bg-white/20 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white sm:size-10"><SiFacebook className="size-4 text-sky-400"/></a></div>
    </div>
    <div className="mx-auto mt-6 flex max-w-[1300px] flex-col gap-2 border-t border-white/10 pt-5 text-xs text-slate-400 sm:flex-row sm:justify-between"><p>Handmade with love in Kenya · © 2026</p><p>M-PESA Till: 8595044</p></div>
  </footer>;
}
